=== max79137913/3D_Render_Library/Final Project/rrv/rrv/dtd/scene.dtd
<!--
/**
 * @file scene.dtd
 * DTD for RadOb project's input data
 * RadOb is free radiosity renderer and visualiser
 * available at http://dudka.cz/devel-PGR
 * @author Kamil Dudka <xdudka00@gmail.com>
 * @author Jakub Filak <filak.jakub@gmail.com>
 */
-->
<!--
    Root element. Obligatory child elements are head and body.
    (similar to HTML)
    
    There are no attributes for now.
    -->
<!ELEMENT scene         (head,body)>

<!--
    Head section of scene. Inside this element can be object's definitions.
    -->
<!ELEMENT head          (objectdef)+>

<!--
    Object's definition. Each object can contain primitive shapes.
    
    name                Object name used for further references.
    file                Name of file where object is defined. When attribute is used then 
                        definition of object in actual file is replaced from other file.
    -->
<!ELEMENT objectdef     (triangleset|cuboid|barrel|globe|teapot)+>
<!ATTLIST objectdef
          name          CDATA #REQUIRED
          file          CDATA #IMPLIED
          >

<!--
    Standalone triangle or 1st triangle inside triangleset element.
    
    radiosity           triangle's color given as three float numbers
    emission            triangle's emission given as three float numbers
    reflectivity        triangle's reflectivity given as three float numbers
    -->
<!ELEMENT triangle      (vertex+)>
<!ATTLIST triangle
          radiosity     CDATA #IMPLIED
          emission      CDATA #IMPLIED
          reflectivity  CDATA #IMPLIED
          >

<!--
    2nd or any next one triangle inside triangleset element.
    Using sematic from opengl when constat GL_TRIANGLES_QUADS is used.
    
    
    radiosity           triangle's color given as three float numbers
    emission            triangle's emission given as three float numbers
    reflectivity        triangle's reflectivity given as three float numbers
    -->
<!ELEMENT trianglenext  (vertex)>
<!ATTLIST trianglenext
          radiosity     CDATA #IMPLIED
          emission      CDATA #IMPLIED
          reflectivity  CDATA #IMPLIED
          >

<!--
    A set of triangles with common edges. (format known from OpenGL API)
    Obligatory child element is 'triangle'.
    
    radiosity           triangle's color given as three float numbers
    emission            triangle's emission given as three float numbers
    reflectivity        triangle's reflectivity given as three float numbers
    -->
<!ELEMENT triangleset   (triangle,trianglenext*)>
<!ATTLIST triangleset
          name          CDATA #IMPLIED
          radiosity     CDATA #IMPLIED
          emission      CDATA #IMPLIED
          reflectivity  CDATA #IMPLIED
          >

<!--
    Triangle's vertex.
    There can't be any child elements.
    
    x                   vertex's x axis
    y                   vertex's y axis
    z                   vertex's z axis
    -->
<!ELEMENT vertex        EMPTY>
<!ATTLIST vertex
          x             CDATA #REQUIRED
          y             CDATA #REQUIRED
          z             CDATA #REQUIRED
          >

<!--
    Cuboid (primitive shape)
    
    radiosity           triangle's color given as three float numbers
    emission            triangle's emission given as three float numbers
    reflectivity        triangle's reflectivity given as three float numbers
    -->
<!ELEMENT cuboid        EMPTY>
<!ATTLIST cuboid
          name          CDATA #IMPLIED
          radiosity     CDATA #IMPLIED
          emission      CDATA #IMPLIED
          reflectivity  CDATA #IMPLIED
          >

<!--
    Barell (primitive shape)
    
    radiosity           triangle's color given as three float numbers
    emission            triangle's emission given as three float numbers
    reflectivity        triangle's reflectivity given as three float numbers
    -->
<!ELEMENT barrel        EMPTY>
<!ATTLIST barrel
          name          CDATA #IMPLIED
          radiosity     CDATA #IMPLIED
          emission      CDATA #IMPLIED
          reflectivity  CDATA #IMPLIED
          >

<!--
    Globe (primitive shape)
    
    radiosity           triangle's color given as three float numbers
    emission            triangle's emission given as three float numbers
    reflectivity        triangle's reflectivity given as three float numbers
    -->
<!ELEMENT globe         EMPTY>
<!ATTLIST globe
          name          CDATA #IMPLIED
          radiosity     CDATA #IMPLIED
          emission      CDATA #IMPLIED
          reflectivity  CDATA #IMPLIED
          >

<!--
    Teapot (primitive shape)
    
    radiosity           triangle's color given as three float numbers
    emission            triangle's emission given as three float numbers
    reflectivity        triangle's reflectivity given as three float numbers
    -->
<!ELEMENT teapot        EMPTY>
<!ATTLIST teapot
          name          CDATA #IMPLIED
          radiosity     CDATA #IMPLIED
          emission      CDATA #IMPLIED
          reflectivity  CDATA #IMPLIED
          >

<!--
    Body section of scene. There can be object's references or its trasformations.
    -->
<!ELEMENT body          (object|rotate|translate|scale|shear)+>

<!--
    Object's reference. Object has to be defined inside head section.
    -->
<!ELEMENT object        EMPTY>
<!ATTLIST object
          name          CDATA #REQUIRED
          >

<!--
    Rotation (transformation)
    
    angle               angle of rotation
    dx, dy, dz          rotation's vector
    -->
<!ELEMENT rotate        (object|rotate|translate|scale|shear)+>
<!ATTLIST rotate
          angle         CDATA #IMPLIED
          dx            CDATA #IMPLIED
          dy            CDATA #IMPLIED
          dz            CDATA #IMPLIED
          >

<!--
    Translation (transformation)
    
    dx, dy, dz          translation vector
    -->
<!ELEMENT translate     (object|rotate|translate|scale|shear)+>
<!ATTLIST translate
          dx            CDATA #IMPLIED
          dy            CDATA #IMPLIED
          dz            CDATA #IMPLIED
          >

<!--
    Scale (transformation)
    
    dx, dy, dz          scale vector
    -->
<!ELEMENT scale         (object|rotate|translate|scale|shear)+>
<!ATTLIST scale
          dx            CDATA #IMPLIED
          dy            CDATA #IMPLIED
          dz            CDATA #IMPLIED
          >

<!--
    Shear (transformation)
    
    dx, dy, dz          shear vector
    -->
<!ELEMENT shear         (object|rotate|translate|scale|shear)+>
<!ATTLIST shear
          dx            CDATA #IMPLIED
          dy            CDATA #IMPLIED
          dz            CDATA #IMPLIED
          >

=== max79137913/3D_Render_Library/Final Project/rrv/rrv/scene/macro/room3.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE scene SYSTEM "http://dudka.cz/dtd/scene.dtd">
<scene>
	<head>
		<objectdef name="xyplane">
			<triangleset name="first" reflectivity=".9,.9,.9">
				<triangle>
					<vertex x="10.0"  y="-10.0" z="0.0"/>
					<vertex x="10.0"  y="10.0"  z="0.0"/>
					<vertex x="-10.0" y="-10.0" z="0.0"/>
				</triangle>
				<trianglenext>
					<vertex x="-10.0" y="10.0"  z="0.0"/>
				</trianglenext>
			</triangleset>
		</objectdef>
		<objectdef name="xyplane-green">
			<triangleset reflectivity=".6,.6,.6">
				<triangle>
					<vertex x="10.0"  y="-10.0" z="0.0"/>
					<vertex x="10.0"  y="10.0"  z="0.0"/>
					<vertex x="-10.0" y="-10.0" z="0.0"/>
				</triangle>
				<trianglenext>
					<vertex x="-10.0" y="10.0"  z="0.0"/>
				</trianglenext>
			</triangleset>
		</objectdef>
		<objectdef name="black-barrel">
			<barrel reflectivity='.1,.1,.1'/>
		</objectdef>
		<objectdef name="light-source">
			<cuboid emission='1,1,1'/>
		</objectdef>
    <objectdef name="bulb-barrel">
      <barrel reflectivity="1,1,.8"/>
    </objectdef>
    <objectdef name="bulb-globe">
      <globe emission="1,1,.9"/>
    </objectdef>
		<objectdef name='teapot'>
			<teapot reflectivity='.8,.8,0'/>
		</objectdef>
    <objectdef name="pillar">
      <cuboid reflectivity=".9,.9,.9"/>
    </objectdef>
    <objectdef name="table">
      <cuboid reflectivity=".3,.3,.9"/>
    </objectdef>
	</head>
	<body>
		<apply-macro name="viewScene"/>
		
		<!-- Scene definition -->
		<macro name="scene">
			<!-- Room -->
			<apply-macro name="room"/>
      
      <!-- Pillars -->
      <translate dx='5'>
        <apply-macro name="v-pillar"/>
      </translate>
      <translate dz='5'>
        <apply-macro name="v-pillar"/>
      </translate>
      
      <!-- Table -->
      <translate dx='-3' dy='-7' dz='-3'>
        <scale dx='8' dy='4' dz='8'>
          <object name="table"/>
        </scale>
      </translate>
      
      <!-- Teapot -->
      <translate dx='-3' dy='-5' dz='-3'>
        <scale dx='2' dy='1.5' dz='2'>
          <rotate angle='-30' dy='1'>
            <object name='teapot'/>
          </rotate>
        </scale>
      </translate>
			
      <!-- Lights -->
      <translate dy='10'>
        <translate dx='-5' dz='5'>
          <apply-macro name="bulb"/>
        </translate>
        <translate dx='5' dz='-5'>
          <apply-macro name="bulb"/>
        </translate>
      </translate>
      <translate dx='-7' dy='-3' dz='-10'>
        <rotate angle='90' dx='-1'>
          <scale dx='.7' dy='.5' dz='.7'>
            <apply-macro name="bulb"/>
          </scale>
        </rotate>
      </translate>
		</macro>
		
		<!-- View definition -->
		<macro name="viewScene">
			<!--<translate dx='-2'>
				<rotate angle='60' dy='1'>
					<scale dx='1.5' dy='1.5' dz='1.8'>-->
						<apply-macro name="scene"/>					
					<!--</scale>
				</rotate>
			</translate>-->
		</macro>
		
		<!-- Room definition -->
		<macro name="room">
			<translate dx='10'>
				<rotate angle="90" dx="0" dy="1" dz="0">
					<object name="xyplane"/>
				</rotate>
			</translate>
			<translate dx='-10'>
				<rotate angle="90" dx="0" dy="-1" dz="0">
					<object name="xyplane"/>
				</rotate>
			</translate>
			<translate dz='-10'>
					<object name="xyplane"/>
			</translate>
			<translate dz='10'>
				<rotate angle="180" dx="0" dy="1" dz="0">
					<object name="xyplane"/>
				</rotate>
			</translate>
			<translate dy='10'>
				<rotate angle="90" dx="1" dy="0" dz="0">
					<object name="xyplane"/>
				</rotate>
			</translate>
			<translate dy='-10'>
				<rotate angle="90" dx="-1" dy="0" dz="0">
					<object name="xyplane"/>
<!-- 					<object name="xyplane-green"/> -->
				</rotate>
			</translate>
		</macro>
    
    <macro name="bulb">
      <scale dx="5" dy="5" dz="5">
        <translate dy='-.5'>
          <translate dy='-.5'>
            <object name="bulb-globe"/>
          </translate>
          <scale dx='.5' dy='1' dz='.5'>
            <object name="bulb-barrel"/>
          </scale>
        </translate>
      </scale>
    </macro>
    
    <macro name="v-pillar">
      <scale dx="3" dy="20" dz="3">
        <object name="pillar"/>
      </scale>
    </macro>
	
	</body>
</scene>

=== max79137913/3D_Render_Library/Final Project/rrv/rrv/scene/room2.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE scene SYSTEM "http://dudka.cz/dtd/scene.dtd">
<scene>
<!--Generated by XSLT processor using macro.xsl template-->
  <head>
    <objectdef name="xyplane">
      <triangleset name="first" reflectivity=".9,.9,.9">
        <triangle>
          <vertex x="10.0" y="-10.0" z="0.0"/>
          <vertex x="10.0" y="10.0" z="0.0"/>
          <vertex x="-10.0" y="-10.0" z="0.0"/>
        </triangle>
        <trianglenext>
          <vertex x="-10.0" y="10.0" z="0.0"/>
        </trianglenext>
      </triangleset>
    </objectdef>
    <objectdef name="xyplane-green">
      <triangleset reflectivity=".6,.6,.6">
        <triangle>
          <vertex x="10.0" y="-10.0" z="0.0"/>
          <vertex x="10.0" y="10.0" z="0.0"/>
          <vertex x="-10.0" y="-10.0" z="0.0"/>
        </triangle>
        <trianglenext>
          <vertex x="-10.0" y="10.0" z="0.0"/>
        </trianglenext>
      </triangleset>
    </objectdef>
    <objectdef name="black-barrel">
      <barrel reflectivity=".1,.1,.1"/>
    </objectdef>
    <objectdef name="light-source">
      <cuboid emission="1,1,1"/>
    </objectdef>
<!--<objectdef name='table'>
			<cuboid emission='0,0,.3' reflectivity='0,0,0' radiosity='0,0,0'/>
		</objectdef>-->
    <objectdef name="teapot">
      <teapot reflectivity=".8,.8,0"/>
    </objectdef>
<!--<objectdef name='light'>
			<barrel emission='.5,.5,.6' reflectivity='0,0,0' radiosity='0,0,0'/>
		</objectdef>-->
  </head>
  <body>
<!--Start of macro execution: viewScene-->
    <translate dx="-2">
      <rotate angle="60" dy="1">
        <scale dx="1.5" dy="1.5" dz="1.8">
<!--Start of macro execution: scene-->
<!--Start of macro execution: room-->
          <translate dx="10">
            <rotate angle="90" dx="0" dy="1" dz="0">
              <object name="xyplane"/>
            </rotate>
          </translate>
          <translate dx="-10">
            <rotate angle="90" dx="0" dy="-1" dz="0">
              <object name="xyplane"/>
            </rotate>
          </translate>
          <translate dz="-10">
            <object name="xyplane"/>
          </translate>
          <translate dz="10">
            <rotate angle="180" dx="0" dy="1" dz="0">
              <object name="xyplane"/>
            </rotate>
          </translate>
          <translate dy="10">
            <rotate angle="90" dx="1" dy="0" dz="0">
              <object name="xyplane"/>
            </rotate>
          </translate>
          <translate dy="-10">
            <rotate angle="90" dx="-1" dy="0" dz="0">
              <object name="xyplane-green"/>
            </rotate>
          </translate>
<!--End of macro execution: room-->
          <translate dy="6" dz="4">
<!--Start of macro execution: light-->
            <translate dx="-1.5" dy="2">
              <scale dx="1" dz="1" dy="4">
                <object name="black-barrel"/>
              </scale>
            </translate>
            <translate dx="1.5" dy="2">
              <scale dx="1" dz="1" dy="4">
                <object name="black-barrel"/>
              </scale>
            </translate>
            <translate dy="-1">
              <scale dx="6" dz="4" dy="2">
                <object name="light-source"/>
              </scale>
            </translate>
<!--End of macro execution: light-->
          </translate>
          <translate dy="6" dz="-4">
<!--Start of macro execution: light-->
            <translate dx="-1.5" dy="2">
              <scale dx="1" dz="1" dy="4">
                <object name="black-barrel"/>
              </scale>
            </translate>
            <translate dx="1.5" dy="2">
              <scale dx="1" dz="1" dy="4">
                <object name="black-barrel"/>
              </scale>
            </translate>
            <translate dy="-1">
              <scale dx="6" dz="4" dy="2">
                <object name="light-source"/>
              </scale>
            </translate>
<!--End of macro execution: light-->
          </translate>
          <translate dy="-8" dz="5">
            <rotate angle="45" dy="-1">
              <scale dx="2" dy="2" dz="2">
                <object name="teapot"/>
              </scale>
            </rotate>
          </translate>
<!--End of macro execution: scene-->
        </scale>
      </rotate>
    </translate>
<!--End of macro execution: viewScene-->
<!--Defined macro: scene-->
<!--Defined macro: viewScene-->
<!--Defined macro: room-->
<!--Defined macro: light-->
  </body>
</scene>

=== max79137913/3D_Render_Library/Final Project/rrv/rrv/scene/macro/room2.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE scene SYSTEM "http://dudka.cz/dtd/scene.dtd">
<scene>
	<head>
		<objectdef name="xyplane">
			<triangleset name="first" reflectivity=".9,.9,.9">
				<triangle>
					<vertex x="10.0"  y="-10.0" z="0.0"/>
					<vertex x="10.0"  y="10.0"  z="0.0"/>
					<vertex x="-10.0" y="-10.0" z="0.0"/>
				</triangle>
				<trianglenext>
					<vertex x="-10.0" y="10.0"  z="0.0"/>
				</trianglenext>
			</triangleset>
		</objectdef>
		<objectdef name="xyplane-green">
			<triangleset reflectivity=".6,.6,.6">
				<triangle>
					<vertex x="10.0"  y="-10.0" z="0.0"/>
					<vertex x="10.0"  y="10.0"  z="0.0"/>
					<vertex x="-10.0" y="-10.0" z="0.0"/>
				</triangle>
				<trianglenext>
					<vertex x="-10.0" y="10.0"  z="0.0"/>
				</trianglenext>
			</triangleset>
		</objectdef>
		<objectdef name="black-barrel">
			<barrel reflectivity='.1,.1,.1'/>
		</objectdef>
		<objectdef name="light-source">
			<cuboid emission='1,1,1'/>
		</objectdef>
		<!--<objectdef name='table'>
			<cuboid emission='0,0,.3' reflectivity='0,0,0' radiosity='0,0,0'/>
		</objectdef>-->
		<objectdef name='teapot'>
			<teapot reflectivity='.8,.8,0'/>
		</objectdef>
		<!--<objectdef name='light'>
			<barrel emission='.5,.5,.6' reflectivity='0,0,0' radiosity='0,0,0'/>
		</objectdef>-->
	</head>
	<body>
		<apply-macro name="viewScene"/>
		
		<!-- Scene definition -->
		<macro name="scene">
			<!-- Room -->
			<apply-macro name="room"/>
			
			<!-- Light 1 -->
			<translate dy='6' dz='4'>
				<apply-macro name="light"/>
			</translate>
			
			<!-- Light 2 -->
			<translate dy='6' dz='-4'>
				<apply-macro name="light"/>
			</translate>
			
			<!-- Teapot -->
			<translate dy='-8' dz='5'>
				<rotate angle='45' dy='-1'>
					<scale dx='2' dy='2' dz='2'>
						<object name='teapot'/>
					</scale>
				</rotate>
			</translate>
		</macro>
		
		<!-- View definition -->
		<macro name="viewScene">
			<translate dx='-2'>
				<rotate angle='60' dy='1'>
					<scale dx='1.5' dy='1.5' dz='1.8'>
						<apply-macro name="scene"/>					
					</scale>
				</rotate>
			</translate>
		</macro>
		
		<!-- Room definition -->
		<macro name="room">
			<translate dx='10'>
				<rotate angle="90" dx="0" dy="1" dz="0">
					<object name="xyplane"/>
				</rotate>
			</translate>
			<translate dx='-10'>
				<rotate angle="90" dx="0" dy="-1" dz="0">
					<object name="xyplane"/>
				</rotate>
			</translate>
			<translate dz='-10'>
					<object name="xyplane"/>
			</translate>
			<translate dz='10'>
				<rotate angle="180" dx="0" dy="1" dz="0">
					<object name="xyplane"/>
				</rotate>
			</translate>
			<translate dy='10'>
				<rotate angle="90" dx="1" dy="0" dz="0">
					<object name="xyplane"/>
				</rotate>
			</translate>
			<translate dy='-10'>
				<rotate angle="90" dx="-1" dy="0" dz="0">
					<object name="xyplane-green"/>
				</rotate>
			</translate>
		</macro>
		
		<!-- Light definition -->
		<macro name="light">
			<translate dx='-1.5' dy='2'>
				<scale dx='1' dz='1' dy='4'>
					<object name='black-barrel'/>
				</scale>
			</translate>
			<translate dx='1.5' dy='2'>
				<scale dx='1' dz='1' dy='4'>
					<object name='black-barrel'/>
				</scale>
			</translate>
			<translate dy='-1'>
				<scale dx='6' dz='4' dy='2'>
					<object name='light-source'/>
				</scale>
			</translate>
		</macro>
	</body>
</scene>

=== max79137913/3D_Render_Library/Final Project/rrv/rrv/scene/room3.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE scene SYSTEM "http://dudka.cz/dtd/scene.dtd">
<scene>
<!--Generated by XSLT processor using macro.xsl template-->
  <head>
    <objectdef name="xyplane">
      <triangleset name="first" reflectivity=".9,.9,.9">
        <triangle>
          <vertex x="10.0" y="-10.0" z="0.0"/>
          <vertex x="10.0" y="10.0" z="0.0"/>
          <vertex x="-10.0" y="-10.0" z="0.0"/>
        </triangle>
        <trianglenext>
          <vertex x="-10.0" y="10.0" z="0.0"/>
        </trianglenext>
      </triangleset>
    </objectdef>
    <objectdef name="xyplane-green">
      <triangleset reflectivity=".6,.6,.6">
        <triangle>
          <vertex x="10.0" y="-10.0" z="0.0"/>
          <vertex x="10.0" y="10.0" z="0.0"/>
          <vertex x="-10.0" y="-10.0" z="0.0"/>
        </triangle>
        <trianglenext>
          <vertex x="-10.0" y="10.0" z="0.0"/>
        </trianglenext>
      </triangleset>
    </objectdef>
    <objectdef name="black-barrel">
      <barrel reflectivity=".1,.1,.1"/>
    </objectdef>
    <objectdef name="light-source">
      <cuboid emission="1,1,1"/>
    </objectdef>
    <objectdef name="bulb-barrel">
      <barrel reflectivity="1,1,.8"/>
    </objectdef>
    <objectdef name="bulb-globe">
      <globe emission="1,1,.9"/>
    </objectdef>
    <objectdef name="teapot">
      <teapot reflectivity=".8,.8,0"/>
    </objectdef>
    <objectdef name="pillar">
      <cuboid reflectivity=".9,.9,.9"/>
    </objectdef>
    <objectdef name="table">
      <cuboid reflectivity=".3,.3,.9"/>
    </objectdef>
  </head>
  <body>
<!--Start of macro execution: viewScene-->
<!--Start of macro execution: scene-->
<!--Start of macro execution: room-->
    <translate dx="10">
      <rotate angle="90" dx="0" dy="1" dz="0">
        <object name="xyplane"/>
      </rotate>
    </translate>
    <translate dx="-10">
      <rotate angle="90" dx="0" dy="-1" dz="0">
        <object name="xyplane"/>
      </rotate>
    </translate>
    <translate dz="-10">
      <object name="xyplane"/>
    </translate>
    <translate dz="10">
      <rotate angle="180" dx="0" dy="1" dz="0">
        <object name="xyplane"/>
      </rotate>
    </translate>
    <translate dy="10">
      <rotate angle="90" dx="1" dy="0" dz="0">
        <object name="xyplane"/>
      </rotate>
    </translate>
    <translate dy="-10">
      <rotate angle="90" dx="-1" dy="0" dz="0">
        <object name="xyplane"/>
      </rotate>
    </translate>
<!--End of macro execution: room-->
    <translate dx="5">
<!--Start of macro execution: v-pillar-->
      <scale dx="3" dy="20" dz="3">
        <object name="pillar"/>
      </scale>
<!--End of macro execution: v-pillar-->
    </translate>
    <translate dz="5">
<!--Start of macro execution: v-pillar-->
      <scale dx="3" dy="20" dz="3">
        <object name="pillar"/>
      </scale>
<!--End of macro execution: v-pillar-->
    </translate>
    <translate dx="-3" dy="-7" dz="-3">
      <scale dx="8" dy="4" dz="8">
        <object name="table"/>
      </scale>
    </translate>
    <translate dx="-3" dy="-5" dz="-3">
      <scale dx="2" dy="1.5" dz="2">
        <rotate angle="-30" dy="1">
          <object name="teapot"/>
        </rotate>
      </scale>
    </translate>
    <translate dy="10">
      <translate dx="-5" dz="5">
<!--Start of macro execution: bulb-->
        <scale dx="5" dy="5" dz="5">
          <translate dy="-.5">
            <translate dy="-.5">
              <object name="bulb-globe"/>
            </translate>
            <scale dx=".5" dy="1" dz=".5">
              <object name="bulb-barrel"/>
            </scale>
          </translate>
        </scale>
<!--End of macro execution: bulb-->
      </translate>
      <translate dx="5" dz="-5">
<!--Start of macro execution: bulb-->
        <scale dx="5" dy="5" dz="5">
          <translate dy="-.5">
            <translate dy="-.5">
              <object name="bulb-globe"/>
            </translate>
            <scale dx=".5" dy="1" dz=".5">
              <object name="bulb-barrel"/>
            </scale>
          </translate>
        </scale>
<!--End of macro execution: bulb-->
      </translate>
    </translate>
    <translate dx="-7" dy="-3" dz="-10">
      <rotate angle="90" dx="-1">
        <scale dx=".7" dy=".5" dz=".7">
<!--Start of macro execution: bulb-->
          <scale dx="5" dy="5" dz="5">
            <translate dy="-.5">
              <translate dy="-.5">
                <object name="bulb-globe"/>
              </translate>
              <scale dx=".5" dy="1" dz=".5">
                <object name="bulb-barrel"/>
              </scale>
            </translate>
          </scale>
<!--End of macro execution: bulb-->
        </scale>
      </rotate>
    </translate>
<!--End of macro execution: scene-->
<!--End of macro execution: viewScene-->
<!--Defined macro: scene-->
<!--Defined macro: viewScene-->
<!--Defined macro: room-->
<!--Defined macro: bulb-->
<!--Defined macro: v-pillar-->
  </body>
</scene>
